config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  resources :shops
  resources :cart_items, only: [:index] do
    get :add, :checkout, on: :collection
  end

  root to: 'products#index'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :cart_items

  validates :user, :presence => true
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart

  validates :cart, :presence => true
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :price, :presence => true
end

app/models/shop.rb
class Shop < ActiveRecord::Base

  after_create :create_tenant

  validates :name, :subdomain, :presence => true

  private

  def create_tenant
    Apartment::Tenant.create(subdomain)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :cart

  validates :email, :presence => true

  after_create :create_cart

  private

  def create_cart
    Cart.create!({user_id: self.id})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def validate_admin
    unless current_user.is_admin?
      redirect_to root_path, notice: 'You do not have access to this page!'
    end
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def index
    @cart = current_user.cart
  end

  def add
    CartItem.create!({ cart_id: current_user.cart.id, product_id: params[:product_id].to_i })
    redirect_to products_path, notice: 'Product added to cart!'
  rescue => ex
    # todo: notify to exception tracking site for dev use
    redirect_to products_path, notice: 'Some error occurred in adding product to cart, please try again!'
  end

  def checkout
    redirect_to products_path, notice: 'No item in your cart please add some product to cart!' and return if current_user.cart.cart_items.blank?

    current_user.cart.cart_items.destroy_all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :validate_admin, only: [:new, :create, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  before_action :validate_admin

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :subdomain)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/cart_items/checkout.html.erb
<div class="container">
  <h2>Thank you for shopping with MultiShop, your order will reach soon.</h2>
  <%= link_to 'Shop More', root_path, :class => 'btn btn-primary' %>
</div>

app/views/cart_items/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h2>Products in Cart</h2>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
      <% @cart.cart_items.each do |cart_item| %>
          <tr>
            <!-- Todo: take product form association create many to many association -->
            <% product = Product.find(cart_item.product_id) %>

            <td><%= product.name %></td>
            <td><%= product.price %></td>

            <td><%= link_to 'Show', product %></td>
          </tr>
      <% end %>

      <tr>
        <% if @cart.cart_items.present? %>
          <% price_array = @cart.cart_items.map { |cart_item| product = Product.find(cart_item.product_id).price } %>
        <% end %>
        <td><strong>Total Cost</strong></td>
        <td><%= price_array.sum rescue 'No product in cart.' %></td>
        <td></td>
      </tr>
    </tbody>
  </table>

  <%= link_to 'Checkout', checkout_cart_items_path, :class => 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MultiShop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Multi Shop</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <% if user_signed_in? %>
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_path, :class => 'navbar-link' %></li>

            <% if current_user.is_admin? %>
                <li><%= link_to 'Shop', shops_path, :class => 'navbar-link' %></li>
            <% else %>
                <li><%= link_to 'Cart', cart_items_path, :class => 'navbar-link' %></li>
            <% end %>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li><a href='#'><span class="glyphicon glyphicon-user"></span> <%= current_user.email %> </a></li>
            <li><a href=<%= destroy_user_session_path %> data-method='delete'><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
          </ul>
      <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><a href=<%= new_user_registration_path %>><span class="glyphicon glyphicon-user"></span> Sign Up </a></li>
            <li><a href=<%= new_user_session_path %>><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          </ul>
      <% end %>
    </div>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h2>Available Products</h2>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.price %></td>

            <% if current_user.is_admin? %>
                <td><%= link_to 'Edit', edit_product_path(product) %></td>
                <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% else %>
                <td><%= link_to 'Show', product %></td>
                <td><%= link_to 'Add to Cart', add_cart_items_path(product_id: product.id) %></td>
            <% end %>
          </tr>
      <% end %>
    </tbody>
  </table>
  <br>

  <% if current_user.is_admin? %>
      <%= link_to 'New Product', new_product_path, :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h2>Products Description</h2>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= @product.name %></td>
      <td><%= @product.price %></td>
    </tr>

    <tr>
      <% if current_user.is_admin? %>
          <td><%= link_to 'Edit', edit_product_path(@product) %></td>
      <% else %>
          <td><%= link_to 'Add to Cart', add_cart_items_path(product_id: @product.id) %></td>
      <% end %>
      <td><%= link_to 'Back', products_path %></td>
    </tr>
    </tbody>
  </table>
</div>

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :subdomain %><br>
    <%= f.text_field :subdomain %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h2>All Shops</h2>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Name</th>
      <th>Subdomain</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% @shops.each do |shop| %>
        <tr>
          <td><%= shop.name %></td>
          <td><%= shop.subdomain %></td>
          <td><%= link_to 'Show', shop %></td>
          <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
          <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Shop', new_shop_path, :class => 'btn btn-primary' %>
</div>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shop.name %>
</p>

<p>
  <strong>Subdomain:</strong>
  <%= @shop.subdomain %>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>